### ISSUE TITLE
CI workflow

### ISSUE THREAD

**Issue by OwenBC** [realjaidhaliwal/game-of-life-modern-java#2]
I'm going to attempt to set up a workflow for this project. This will include:

1. Setting up the Java 8 dependency
2. Installing the existing Gradle wrapper
3. Running the existing tests

**Comment by ketdougi** [comment]
For the build failing, do we need to configure it so it works for firefox or can we just rewrite the test so it will work?

**Comment by OwenBC** [comment]
> For the build failing, do we need to configure it so it works for firefox or can we just rewrite the test so it will work?

I'm guessing that this test is failing because it doesn't have a supporting webdriver in the GitHub box. We could either go about trying to fix that, or just delete (or comment out) the test for now.

**Comment by ketdougi** [comment]
> > For the build failing, do we need to configure it so it works for firefox or can we just rewrite the test so it will work?
> 
> I'm guessing that this test is failing because it doesn't have a supporting webdriver in the GitHub box. We could either go about trying to fix that, or just delete (or comment out) the test for now.

Could we use this WebDriverManager to help us automate driver management?
https://github.com/bonigarcia/webdrivermanager
