### ISSUE TITLE
Setup branch protection

### ISSUE THREAD

**Issue by OwenBC** [realjaidhaliwal/game-of-life-modern-java#5]
I don't have the permissions to access this. So this is on you for now @realjaidhaliwal.

Might be worth just giving us full permissions.

**Comment by vijaivir** [comment]
I can't give you higher access than a collaborator as we cannot have multiple owners for individual (free) GitHub accounts. I've set up the branch protection with the following rules but let me know if you want me to change anything:

<img width="664" alt="Screen Shot 2022-02-21 at 1 31 42 PM" src="https://user-images.githubusercontent.com/91633223/154912744-300b8ebe-f863-4052-87d1-739e2a856021.png">

**Comment by OwenBC** [comment]
I don't think branch protection is set up properly.

The PR I just opened, #8, doesn't require a review.

**Comment by vijaivir** [comment]
So are you able to merge onto the master without approval? The way it's set up requires 1 approval before it can be merged onto the master branch. I can change that to be 2 approvals.

**Comment by OwenBC** [comment]
Issue has been figured out, the branch protection rule needs to be changed: main -> master
